name: Vaultier
main: uk.co.jkinc.Vaultier.Vaultier
version: 1.0
depend: [Vault]
authors: [TXTiger]
commands:
  getapikey:
    description: Generate an API key for scheming with OC or CC.
    usage: /<command>
  acceptTransfer:
    description: Accept a transfer
    usage: /<command> (transactionID)
  denyTransfer:
    description: Deny a transfer
    usage: /<command> (transactionID)
  blockTransfer:
    description: Block a player from sending more transactions (do not use directly)
    usage: /<command> (transactionID)
  unblocktransactions:
    description: Unblock a player to allow them to send transactions to your account.
    usage: /<command> (player)